package com.yuanyin.leafnews.modules.news.entity;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.doc_id
     *
     * @mbggenerated
     */
    private String docId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.digest
     *
     * @mbggenerated
     */
    private String digest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.body
     *
     * @mbggenerated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.imgsrc
     *
     * @mbggenerated
     */
    private String imgsrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.key_word
     *
     * @mbggenerated
     */
    private String keyWord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.doc_id
     *
     * @return the value of news.doc_id
     *
     * @mbggenerated
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.doc_id
     *
     * @param docId the value for news.doc_id
     *
     * @mbggenerated
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.digest
     *
     * @return the value of news.digest
     *
     * @mbggenerated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.digest
     *
     * @param digest the value for news.digest
     *
     * @mbggenerated
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.body
     *
     * @return the value of news.body
     *
     * @mbggenerated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.body
     *
     * @param body the value for news.body
     *
     * @mbggenerated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.imgsrc
     *
     * @return the value of news.imgsrc
     *
     * @mbggenerated
     */
    public String getImgsrc() {
        return imgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.imgsrc
     *
     * @param imgsrc the value for news.imgsrc
     *
     * @mbggenerated
     */
    public void setImgsrc(String imgsrc) {
        this.imgsrc = imgsrc == null ? null : imgsrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.time
     *
     * @return the value of news.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.time
     *
     * @param time the value for news.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.type
     *
     * @return the value of news.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.type
     *
     * @param type the value for news.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.key_word
     *
     * @return the value of news.key_word
     *
     * @mbggenerated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.key_word
     *
     * @param keyWord the value for news.key_word
     *
     * @mbggenerated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    @Override
    public String toString() {
        return "News{" +
                "docId='" + docId + '\'' +
                ", title='" + title + '\'' +
                ", digest='" + digest + '\'' +
                ", body='" + body + '\'' +
                ", imgsrc='" + imgsrc + '\'' +
                ", time=" + time +
                ", type='" + type + '\'' +
                ", keyWord='" + keyWord + '\'' +
                '}';
    }
}